### ISSUE TITLE
Problems with build

### ISSUE THREAD

**Issue by JPinkney** [JPinkney/Aimless-Manor#106]
Lighting issues:
- [x] Fix: Some of the objects in the hallway are black instead of actually being lit. Not sure why this is

Inventory issues:
- [x] Fix: Objects are able to be dropped but they do not show on the actual screen

General player issues:
- [x] Fix: Mouse is always showing in the middle of the screen

**Comment by natalielh** [comment]
- [x] Another problem: Cube UI component is very small and not centered in the top of the screen on Mac build

**Comment by natalielh** [comment]
Hallway objects being black could be because the reflection probes are not in the correct place, and the lighting needs to be rebuilt.

Inventory camera fixed by making sure its depth is "2", and the main camera "1".
